<?php
/**
 * Created by PhpStorm.
 * User: Grey
 * Date: 2019/6/18
 * Time: 17:54
 */

namespace app\vote\controller;

use think\Controller;
use app\api\controller\Send;
use \app\vote\controller\api\VoteMain;

/**
 * Class Vote
 * @package app\vote\controller
 */
class Vote extends Controller
{
    use Send;

    private $mainController;

    /**
     * 初始化方法
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->mainController = new VoteMain();     // 实例化需要的方法
    }

    /**
     * 投票创建方法
     */
    public function postVoteCreat()
    {
        $result = $this->mainController->createVote();

        if ($result === 'fail') {

            return self::returnMsg(500, 'fail', '添加失败，请稍后再试');
        }
        return self::returnMsg(200, 'success', $result);
    }

    /**
     * 投票查询方法
     */
    public function getVoteMain()
    {
        $result = $this->mainController->findVote();

        if ($result == null) {

            return self::returnMsg(500, 'fail', '尚未添加该投票，请进行添加');
        }
        return self::returnMsg(200, 'success', $result);
    }

    /**
     * 投票修改方法
     */
    public function postVoteEdit()
    {
        $result = $this->mainController->updateVote();

        if ($result === 'fail') {

            return self::returnMsg(500, 'fail', '添加失败，请稍后再试');
        }
        return self::returnMsg(200, 'success', $result);
    }

    /**
     * 投票删除方法
     */
    public function postVoteDel()
    {
        $result = $this->mainController->deleteVote();

        if ($result === 'fail') {

            return self::returnMsg(500, 'fail', '添加失败，请稍后再试');
        }
        return self::returnMsg(200, 'success', $result);
    }
}