<?php
/**
 * Created by PhpStorm.
 * User: Grey
 * Date: 2019/6/18
 * Time: 11:04
 */

namespace app\custom\controller;

use think\Controller;
use \app\custom\controller\api\CustomMain;
use \app\api\controller\Send;

class Custom extends Controller
{
    use Send;

    /**
     * 相关方法对象
     * @var Object
     */
    protected $mainController;

    /**
     * 初始化方法
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->mainController = new CustomMain();     // 实例化需要的方法
    }

    /**
     * 客户添加
     */
    public function postCustomCreat()
    {
        $result = $this->mainController->createCustom();

        if ($result === 'fail') {

            return self::returnMsg(500, 'fail', '添加失败，请稍后再试');
        }
        return self::returnMsg(200, 'success', $result);
    }

    /**
     * 客户查询方法
     */
    public function getCustomMain()
    {
        $result = $this->mainController->findCustom();

        if ($result == null) {

            return self::returnMsg(500, 'fail', '尚未添加该客户，请进行添加');
        }
        return self::returnMsg(200, 'success', $result);
    }

    /**
     * 客户修改方法
     */
    public function postCustomEdit()
    {
        $result = $this->mainController->updateCustom();

        if ($result == 0) {

            return self::returnMsg(500, 'fail', '没有数据改动，请检查传递的详细数据');
        }
        return self::returnMsg(200, 'success', '修改成功');

    }

    /**
     * 客户删除方法
     */
    public function postCustomDel()
    {
        $result = $this->mainController->deleteCustom();

        if ($result !== 1) {

            return self::returnMsg(500, 'fail', '删除失败，请检查传递id');
        }
        return self::returnMsg(200, 'success', '删除成功');
    }
}