<?php
/**
 * Created by PhpStorm.
 * User: Grey
 * Date: 2019/6/19
 * Time: 17:06
 */

namespace app\candidate\controller;

use think\Controller;
use app\api\controller\Send;
use app\candidate\controller\api\CandidateMain as CandidateMain;

/**
 * Class Candidate
 * @package app\candidate\controller
 */
class Candidate extends Controller
{
    use Send;

    private $mainController;

    /**
     * 初始化方法
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->mainController = new CandidateMain();     // 实例化需要的方法
    }

    /**
     * 添加投票候选人方法
     * @return mixed
     */
    public function postCandidateAdd()
    {
        $result = $this->mainController->insertCandidate();

        if ($result === 'fail') {

            return self::returnMsg(500, 'fail', '添加失败，请稍后再试');
        }
        return self::returnMsg(200, 'success', $result);
    }
}