<?php
/**
 * Created by PhpStorm.
 * User: Grey
 * Date: 2019/6/20
 * Time: 9:56
 */

namespace app\user\controller;

use think\Controller;
use app\api\controller\Send;
use app\user\controller\api\UserMain;
use app\user\controller\api\UserVote;

/**
 * Class User
 * @package app\user\controller
 */
class User extends Controller
{
    use Send;

    private $mainController;

    /**
     * 初始化方法
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->mainController = new UserMain();     // 实例化需要的方法
    }

    /**
     * 保密投票用户列表插入方法
     */
    public function postInsertPrivate()
    {
        $result = $this->mainController->doInsertPrivate();

        if ($result !== 'success') {

            return self::returnMsg(500, 'fail', $result);
        }
        return self::returnMsg(200, 'success', '手机号码添加成功');
    }

    /**
     * 删除指定投票用户方法
     */
    public function postDelPrivate()
    {
        $result = $this->mainController->delPrivateMobile();

        if ($result !== 'success') {

            return self::returnMsg(500, 'fail', $result);
        }
        return self::returnMsg(200, 'success', '投票用户删除成功');
    }

    /**
     * 获取投票列表方法
     */
    public function getVoteList()
    {
        $result = $this->mainController->fetchVote();

        if ($result === 'fail') {

            return self::returnMsg(500, 'fail', '添加失败，请稍后再试');
        }
        return self::returnMsg(200, 'success', $result);
    }

    /**
     * 用户进行投票方法
     */
    public function postToVote()
    {
        $vote = new UserVote;

        $result = $vote->insertVote();

        if ($result === 'fail') {

            return self::returnMsg(500, 'fail', '添加失败，请稍后再试');
        }
        return self::returnMsg(200, 'success', $result);
    }
}